version: '3'

services:
  scrapy:
    build: .
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017  # Đảm bảo rằng giá trị này là chính xác
    networks:
      - scrapy_network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - scrapy_network

networks:
  scrapy_network:
    driver: bridge
