version: '3.8'

services:
  scrapy:
    build: .
    volumes:
      - .:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
